version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=admin
  nginx:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "3060:80"
  api:
    deploy:
      replicas: 3
    build:
      dockerfile: Dockerfile
      context: "./server"
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=admin
      - PGPORT=5432
